/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Answers: typeof import('./src/components/Answers.vue')['default']
    FlashMessage: typeof import('./src/components/FlashMessage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    OneAnswer: typeof import('./src/components/OneAnswer.vue')['default']
    OneQuestion: typeof import('./src/components/OneQuestion.vue')['default']
    OneSurvey: typeof import('./src/components/OneSurvey.vue')['default']
    Questions: typeof import('./src/components/Questions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    Surveys: typeof import('./src/components/Surveys.vue')['default']
  }
}
